version: "3.9"

services:

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: "a159S-dnSraikSoxeAJaEg"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - fullstack_net
    restart: always

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "8000:8000"
    networks:
      - fullstack_net
    restart: always
    depends_on:
      - kafka

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    env_file:
      - .env
    networks:
      - fullstack_net
    depends_on:
      - kafka
    restart: always

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    env_file:
      - .env
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - fullstack_net
    depends_on:
      - kafka
    restart: always

networks:
  fullstack_net:
    driver: bridge

volumes:
  kafka_data:
